### ISSUE TITLE
Will there be pie?

### ISSUE THREAD

**Issue by BrianHicks** [elm-conf-us/2016-q-and-a#1]
### Who's This For? (Speaker or Talk Title or just a general question?)

General question

### What's the question?

I like pie.

---

Please use the +1 reaction button below to vote on this question so we can sort and answer the most common questions during the Q&A session. +1 comments will be deleted. Thanks!

**Comment by BrianHicks** [comment]
Woo! Looks like it worked, closing!

**Comment by lukewestby** [comment]
wait i want to know the answer to this

**Comment by BrianHicks** [comment]
I mean I'm not bringing any but you're welcome to.

**Comment by BrianHicks** [comment]
Start an #iwantpie in the Strange Loop Slack. ;)

**Comment by lukewestby** [comment]
Bring The Pie You Want To See In The World™

**Comment by BrianHicks** [comment]
new conference motto

**Comment by fredcy** [comment]
There should at least be French Toast.
